version: '3'
services:
  web:
    build: .
    container_name: nestjs_web
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - db
    restart: always
    volumes:
      - /Users/softone/code/nestjs-project:/usr/src/app
  db:
    container_name: nestjs_db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nestjs
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
