version: '3'
services:
  web:
    build: .
    container_name: nestjs_web
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/usr/src/app
  db:
    container_name: nestjs_db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nestjs
      MYSQL_USER: nestjs_root
      MYSQL_PASSWORD: 123456
  nginx:
    container_name: nestjs_nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443